---
fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/martyewings/provision.git'
    deploy_pe: 'git://github.com/jarretlavallee/puppet-deploy_pe.git'
    ruby_task_helper: "https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper"
    bootstrap: "https://github.com/puppetlabs/puppetlabs-bootstrap"
    puppet_conf: "https://github.com/puppetlabs/puppetlabs-puppet_conf"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
